apiVersion: apps/v1
kind: Deployment



metadata:
  name:  myapp-deployment
  labels:
    app: spring-music



spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-music
  template:
   metadata:
      name:  first-pod
      labels:
         app: spring-music
   spec:
    containers:
      - name: spring-music
        image:  yanivomc/spring-music:latest
        ports:
         - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: spring-music
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: myapp-ClusterIP-service
spec:
  selector:
    app: spring-music
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8090


---

apiVersion: apps/v1
kind: Deployment



metadata:
  name:  myapp-deployment
  labels:
    app: spring-music



spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-music
  template:
   metadata:
      name:  first-pod
      labels:
         app: spring-music
   spec:
    containers:
      - name: spring-music
        image:  yanivomc/spring-music:latest
        ports:
         - containerPort: 8080
---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingrees
  annotations:
    kuberntes.io/ingrees.class: nginx
    nginx.ingrees.kuberntes.io/ssl-redirect: "false"
    nginx.ingrees.kuberntes.io/use-regex: "true"
    nginx.ingrees.kuberntes.io/rewrite-target: /$1
spec:
  rules:
  - host: https://127.0.0.1/music
    http:
      paths:
      - path: /hello-world-one(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ask-helloworld-one
            port:
              -path:

      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: ask-helloworld-one
            port:
              number: 80
