apiVersion: apps/v1
kind: Deployment



metadata:
  name:  myapp-deployment
  labels:
    app: spring-music



spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-music
  template:
   metadata:
      name:  first-pod
      labels:
         app: spring-music
   spec:
    containers:
      - name: spring-music
        image:  yanivomc/spring-music:latest
        ports:
         - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: spring-music
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
        
